import type { ShipState, Task } from "./types.ts";
const rules = `Use only approved project scope. User constraints are not hypotheses. Do not change acceptance checks, commit, push, deploy, or edit controller files. Return ONLY the requested JSON as your final answer, without Markdown fences. Intermediate tool use is allowed. Worktrees are not security sandboxes.`;
export function plannerPrompt(project: string): string {
  return `${rules}\nYou are the planner. Inspect but do not modify source. Produce a small roadmap of milestone → demoable slice → focused task. Every task needs executable acceptance checks; never invent a passing manual playtest. Keep the plan within 3 milestones, 3 slices per milestone, 5 tasks per slice. IDs are M001, S01, T01 (task IDs are slice-local). Distinguish objective (stable intended outcome) from goal (implementation approach). Include only known task dependencies, using T01 within the same slice or a qualified M001/S01/T01 key across slices; dependencies may refer to later listed tasks but must form a DAG. List affected domains/files only when known, semantic taskType (reconnaissance, planning-design, implementation, bugfix, refactor, test, documentation, migration, integration, review, research, configuration, security-review), uncertainty (LOW, MEDIUM, HIGH, UNKNOWN), and verificationRequirements. Unknown scope must remain unspecified rather than invented. The controller classifies complexity, risk, parallel eligibility and execution route; do not supply these or any status/attempts.\nBRIEF:\n${project}\nReturn {"milestones":[{"id":"M001","title":"...","outcome":"...","slices":[{"id":"S01","title":"...","tasks":[{"id":"T01","title":"...","objective":"...","goal":"...","dependencies":[],"acceptance":["..."],"affectedDomains":[],"affectedFiles":[],"taskType":"implementation","uncertainty":"UNKNOWN","verificationRequirements":["..."],"verificationCommands":["..."]}]}]}]}.`;
}
export function executorPrompt(project: string, state: ShipState, task: Task): string {
  return `${rules}\nYou are the executor. Implement exactly this task in the worktree. Do not launch detached/background processes. Preserve acceptance checks; the controller runs them independently.\nBRIEF:\n${project}\nTASK:\n${JSON.stringify(task)}\nLATEST FAILURE (repair this, not the check):\n${task.lastError ?? "none"}\nKNOWLEDGE (agent entries are unverified claims unless supported):\n${JSON.stringify(state.knowledge?.slice(-20)).slice(-16000)}\nReturn {"summary":"what changed", "observations":["evidence-backed discoveries, or none"]}.`;
}
export function reviewPrompt(project: string, state: ShipState, slice: string, summaries: string): string {
  return `${rules}\nReview completed slice ${slice}; inspect but do not modify source. Reevaluate the implementation approach for UNSTARTED tasks using captures, evidence, and decisions. This MVP permits only refining task goals; it does not permit dropping outcomes, changing checks, reordering, or adding scope. No change is a valid result. Label inferences and cite concrete evidence. Captures are not authorization to drop requirements.\nBRIEF:\n${project}\nROADMAP:\n${JSON.stringify(state.milestones)}\nKNOWLEDGE:\n${JSON.stringify(state.knowledge?.slice(-30)).slice(-20000)}\nCOMPLETED WORK:\n${summaries}\nReturn {"revision":${state.roadmapRevision},"rationale":"...","lessons":[{"kind":"lesson","text":"...","evidence":"task result or capture ID"}],"changes":[{"task":"M002/S01/T01","goal":"revised implementation approach preserving all acceptance", "reason":"..."}]}. Empty lessons/changes arrays are allowed.`;
}
