const rules = `Plan only the explicit current user request and approved context; a requested change is not approved for execution until proposal approval. User constraints are not hypotheses. Do not weaken acceptance checks, commit, push, deploy, or edit SHIP state files. Return ONLY the requested JSON as your final answer, without Markdown fences. Intermediate tool use is allowed. OMP's checkout is not a security sandbox.`;
export function plannerPrompt(project: string, revision = false): string {
  const brief = revision
    ? `You are revising an existing roadmap for the current user request. Inspect but do not modify source. Preserve stable IDs and completed/started work. Return roadmap operations only: add-milestone, add-slice, add-task, revise-task, split-task, or set-status, referencing existing IDs with qualified M001/S01/T01 task keys and M001/S01 slice keys. Each new task uses the same task schema below; include a concise impactedSummary explaining affected scope and any futureMilestones outline. Do not rewrite the whole roadmap or replace its existing lifecycle state.`
    : `You are drafting the FIRST executable slice, with only immediately actionable bounded work; future outcomes belong in futureMilestones as a short non-executable outline. Do not execute or assume approval.`;
  return `${rules}\n${brief} Inspect but do not modify source. Code tasks require real executable verification commands; research, design, reconnaissance and documentation may use verificationCommands [] only with a substantive workspace artifact, an answer and supported findings for every acceptance criterion. Explicit human evaluation must be approved in the main session. Never invent a passing command or manual playtest. Keep executable work focused (at most 24 new pending tasks). IDs are M001, S01, T01 (task IDs are slice-local). Distinguish objective (stable intended outcome) from goal (implementation approach). Include only known task dependencies, using T01 within the same slice or a qualified M001/S01/T01 key across slices; dependencies may refer to later listed tasks but must form a DAG. List affected domains/files only when known, semantic taskType (reconnaissance, planning-design, implementation, bugfix, refactor, test, documentation, migration, integration, review, research, configuration, security-review), uncertainty (LOW, MEDIUM, HIGH, UNKNOWN), and verificationRequirements. For each new task supply profile complexity, uncertainty and risk as integers 1-10 (1 least, 10 greatest), traits as concise semantic labels, and rationale explaining the complexity/risk score. Unknown scope must remain unspecified rather than invented. SHIP independently derives safety classification, parallel eligibility and execution route; never supply lifecycle fields or override checks.\nBRIEF:\n${project}\n${revision
    ? `Return {"operations":[{"type":"add-task","slice":"M001/S01","task":{"id":"T02","title":"...","objective":"...","goal":"...","dependencies":[],"acceptance":["..."],"affectedDomains":[],"affectedFiles":[],"taskType":"implementation","uncertainty":"UNKNOWN","profile":{"complexity":5,"uncertainty":5,"risk":5,"traits":[],"rationale":["Bounded task"]},"verificationRequirements":["..."],"verificationCommands":["..."]}}],"impactedSummary":["..."],"futureMilestones":[{"id":"M002","title":"...","outcome":"...","approach":"..."}]}. Include futureMilestones only when changing the future outline; set-status cannot mark work passed.`
    : `Return {"milestones":[{"id":"M001","title":"...","outcome":"...","slices":[{"id":"S01","title":"...","tasks":[{"id":"T01","title":"...","objective":"...","goal":"...","dependencies":[],"acceptance":["..."],"affectedDomains":[],"affectedFiles":[],"taskType":"implementation","uncertainty":"UNKNOWN","profile":{"complexity":5,"uncertainty":5,"risk":5,"traits":[],"rationale":["Bounded task"]},"verificationRequirements":["..."],"verificationCommands":["..."]}]}]}],"futureMilestones":[{"id":"M002","title":"...","outcome":"...","approach":"..."}],"impactedSummary":["..."]}. Future milestones are descriptions only, not executable tasks.`}`;
}
